/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managerMenu.item;

import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author syuuta
 */
public class ManageItemBoundary extends javax.swing.JFrame {
    private ManageItemControl manageItemControl;
    
    private DefaultTableModel manageItemTableModel;
    private DefaultTableModel addSetMenuTableModel;
    /**
     * Creates new form ManageItemBoundary
     */
    public ManageItemBoundary() {
        initComponents();
    }
    
    /** 初期化 ****************************************************************/
    
    public void setControl(ManageItemControl manageItemControl) {
        this.manageItemControl = manageItemControl;
        initAdditem();
        initManageItem();
        initAddSetMenu();
    }
    
    /**
     * 商品追加画面初期化
     */
    private void initAdditem() {
        manageItemControl.setCategoryComboBox();
    }
    
    /**
     * 商品編集画面初期化
     */
    private void initManageItem() {
        initManageItemTable();
    }
    
    /**
     * セット商品追加画面初期化
     */
    private void initAddSetMenu() {
        initAddSetMenuTable();
    }
    
    /**
     * 商品編集表初期化
     */
    private void initManageItemTable() {
        String[] manageItemTableTitle = {"", ""};   //列見出しを設定してください
        manageItemTableModel = new DefaultTableModel(manageItemTableTitle, 0);
        
        //商品編集画面表初期化
        jTableManageItem.setModel(manageItemTableModel);
        jTableManageItem.setDefaultEditor(Object.class, null);
        setCellHorizontalAlignmentRight(jTableManageItem, 0); //指定した列を右寄せに　詳しくはJavaDoc参照
        
    }
    
    /**
     * セット商品追加画面表初期化
     */
    private void initAddSetMenuTable() {
        String[] addSetMenuTableTitle = {"", ""};
        addSetMenuTableModel = new DefaultTableModel(addSetMenuTableTitle, 0);
        
         //セット商品追加画面表
        jTableAddSetMenuTable.setModel(addSetMenuTableModel);
        jTableAddSetMenuTable.setDefaultEditor(Object.class, null);
        setCellHorizontalAlignmentRight(jTableAddSetMenuTable, 0);  //こちらも同様
    }
    
    /**
     * テーブルの指定した列を右寄せ表示にする
     * @param jTable       設定するテーブル
     * @param culumnNumber 設定する列
     */
    private void setCellHorizontalAlignmentRight(JTable jTable, int culumnNumber) {
        DefaultTableCellRenderer rightCellRenderer = new DefaultTableCellRenderer();
        
        rightCellRenderer.setHorizontalAlignment(JLabel.RIGHT);
        jTable.getColumnModel().getColumn(culumnNumber).setCellRenderer(rightCellRenderer);
    }
    
    /**************************************************************************/
    
    /** 商品追加画面 ***********************************************************/
    
    /**
     * コンボボックスに商品カテゴリを追加
     * @param categoryList 商品カテゴリリスト
     */
    public void setCategoryComboBox(List<Category> categoryList) {
        
        jComboBoxItemCategory.removeAllItems();
        
        for (Category category : categoryList) {
            jComboBoxItemCategory.addItem(category.getCategoryNumber()  + " : " + category.getCategoryName());
        }
    }
    
    /**************************************************************************/
    
    /** ダイアログ *************************************************************/
    
    /**
     * エラーダイアログ表示
     * @param message エラーメッセージ
     * @param title   タイトル
     */
    public void showErrorMessage(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * 確認ダイアログ表示
     * @param message メッセージ
     * @param title 　タイトル
     */
    public void showConfirmMessage(String message, String title) {
        JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * データベースエラー発生時のエラーダイアログ表示
     */
    public void showDBErrorMessage() {
        showErrorMessage("データベースエラーが発生しました", "エラー");
    }

    /**************************************************************************/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAddItem = new javax.swing.JButton();
        jButtonManageItem = new javax.swing.JButton();
        jButtonManageCategoly = new javax.swing.JButton();
        jButtonManageSetMenu = new javax.swing.JButton();
        jPanelCardLayout = new javax.swing.JPanel();
        jPanelAddAitem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxItemCategory = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAddItemName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAddItemPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelManageItem = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManageItem = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSearchItemNumber = new javax.swing.JTextField();
        jButtonSearchItem = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanelManageCategory = new javax.swing.JPanel();
        jPanelMnageSetMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAddSetMenuTable = new javax.swing.JTable();
        jButtonAddSetMenu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldAddSetMenuPrice = new javax.swing.JTextField();
        jButtonAddItemToSetMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel1.setText("商品管理画面");

        jLabel2.setText("従業員名前");

        jLabel3.setText("従業員番号");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jButtonAddItem.setText("商品追加");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jButtonManageItem.setText("商品編集");
        jButtonManageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageItemActionPerformed(evt);
            }
        });

        jButtonManageCategoly.setText("カテゴリ編集");
        jButtonManageCategoly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageCategolyActionPerformed(evt);
            }
        });

        jButtonManageSetMenu.setText("セットメニュー編集");
        jButtonManageSetMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageSetMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonManageCategoly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonManageSetMenu)
                    .addComponent(jButtonManageItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAddItem, jButtonManageCategoly, jButtonManageItem, jButtonManageSetMenu});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonAddItem)
                .addGap(18, 18, 18)
                .addComponent(jButtonManageItem)
                .addGap(18, 18, 18)
                .addComponent(jButtonManageCategoly)
                .addGap(18, 18, 18)
                .addComponent(jButtonManageSetMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCardLayout.setLayout(new java.awt.CardLayout());

        jPanelAddAitem.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel4.setText("商品追加");

        jComboBoxItemCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("商品カテゴリ");

        jLabel6.setText("商品名");

        jLabel7.setText("価格");

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jButton1.setText("商品登録");

        javax.swing.GroupLayout jPanelAddAitemLayout = new javax.swing.GroupLayout(jPanelAddAitem);
        jPanelAddAitem.setLayout(jPanelAddAitemLayout);
        jPanelAddAitemLayout.setHorizontalGroup(
            jPanelAddAitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddAitemLayout.createSequentialGroup()
                .addGroup(jPanelAddAitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddAitemLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddAitemLayout.createSequentialGroup()
                        .addGroup(jPanelAddAitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddAitemLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanelAddAitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBoxItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldAddItemName)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldAddItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelAddAitemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 356, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAddAitemLayout.setVerticalGroup(
            jPanelAddAitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddAitemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAddItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAddItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCardLayout.add(jPanelAddAitem, "card2");

        jPanelManageItem.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel8.setText("商品編集");

        jTableManageItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableManageItem.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableManageItem);
        if (jTableManageItem.getColumnModel().getColumnCount() > 0) {
            jTableManageItem.getColumnModel().getColumn(0).setResizable(false);
            jTableManageItem.getColumnModel().getColumn(1).setResizable(false);
            jTableManageItem.getColumnModel().getColumn(2).setResizable(false);
            jTableManageItem.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel9.setText("商品番号");

        jButtonSearchItem.setText("検索");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        javax.swing.GroupLayout jPanelManageItemLayout = new javax.swing.GroupLayout(jPanelManageItem);
        jPanelManageItem.setLayout(jPanelManageItemLayout);
        jPanelManageItemLayout.setHorizontalGroup(
            jPanelManageItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageItemLayout.createSequentialGroup()
                .addGroup(jPanelManageItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelManageItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                    .addGroup(jPanelManageItemLayout.createSequentialGroup()
                        .addGroup(jPanelManageItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelManageItemLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanelManageItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelManageItemLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldSearchItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSearchItem))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelManageItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelManageItemLayout.setVerticalGroup(
            jPanelManageItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageItemLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelManageItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldSearchItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchItem))
                .addGap(18, 18, 18)
                .addGroup(jPanelManageItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jPanelCardLayout.add(jPanelManageItem, "card3");

        jPanelManageCategory.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanelManageCategoryLayout = new javax.swing.GroupLayout(jPanelManageCategory);
        jPanelManageCategory.setLayout(jPanelManageCategoryLayout);
        jPanelManageCategoryLayout.setHorizontalGroup(
            jPanelManageCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jPanelManageCategoryLayout.setVerticalGroup(
            jPanelManageCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        jPanelCardLayout.add(jPanelManageCategory, "card4");

        jPanelMnageSetMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel10.setText("セットメニュー作成");

        jTableAddSetMenuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAddSetMenuTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableAddSetMenuTable);
        if (jTableAddSetMenuTable.getColumnModel().getColumnCount() > 0) {
            jTableAddSetMenuTable.getColumnModel().getColumn(0).setResizable(false);
            jTableAddSetMenuTable.getColumnModel().getColumn(1).setResizable(false);
            jTableAddSetMenuTable.getColumnModel().getColumn(2).setResizable(false);
            jTableAddSetMenuTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonAddSetMenu.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jButtonAddSetMenu.setText("登録");

        jLabel11.setText("商品番号");

        jLabel12.setText("金額");

        jButtonAddItemToSetMenu.setText("追加");

        javax.swing.GroupLayout jPanelMnageSetMenuLayout = new javax.swing.GroupLayout(jPanelMnageSetMenu);
        jPanelMnageSetMenu.setLayout(jPanelMnageSetMenuLayout);
        jPanelMnageSetMenuLayout.setHorizontalGroup(
            jPanelMnageSetMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMnageSetMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMnageSetMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMnageSetMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAddSetMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMnageSetMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMnageSetMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMnageSetMenuLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddItemToSetMenu))
                            .addGroup(jPanelMnageSetMenuLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAddSetMenuPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMnageSetMenuLayout.setVerticalGroup(
            jPanelMnageSetMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMnageSetMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMnageSetMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddItemToSetMenu))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMnageSetMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldAddSetMenuPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jButtonAddSetMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCardLayout.add(jPanelMnageSetMenu, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jButtonManageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManageItemActionPerformed

    private void jButtonManageCategolyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageCategolyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManageCategolyActionPerformed

    private void jButtonManageSetMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageSetMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManageSetMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageItemBoundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageItemBoundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageItemBoundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageItemBoundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageItemBoundary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonAddItemToSetMenu;
    private javax.swing.JButton jButtonAddSetMenu;
    private javax.swing.JButton jButtonManageCategoly;
    private javax.swing.JButton jButtonManageItem;
    private javax.swing.JButton jButtonManageSetMenu;
    private javax.swing.JButton jButtonSearchItem;
    private javax.swing.JComboBox<String> jComboBoxItemCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAddAitem;
    private javax.swing.JPanel jPanelCardLayout;
    private javax.swing.JPanel jPanelManageCategory;
    private javax.swing.JPanel jPanelManageItem;
    private javax.swing.JPanel jPanelMnageSetMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAddSetMenuTable;
    private javax.swing.JTable jTableManageItem;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldAddItemName;
    private javax.swing.JTextField jTextFieldAddItemPrice;
    private javax.swing.JTextField jTextFieldAddSetMenuPrice;
    private javax.swing.JTextField jTextFieldSearchItemNumber;
    // End of variables declaration//GEN-END:variables
}
