/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sys;

import java.awt.CardLayout;
import java.awt.Color;

/**
 * 従業員メニューバウンダリー
 * @author 19jz0115
 */
public class MainMenuBoundary extends javax.swing.JFrame {
    private static final String CARD_MEIN_MENU = "card2";
    private static final String CARD_EMPLOYEES_MENU = "card3";
    private static final String CARD_MANAGER_MENU = "card4";
    private static final String CARD_LOGIN_MENU = "card5";
    private SystemControl control;
    private final CardLayout cardLayout;
    
    
    public MainMenuBoundary() {
        initComponents();
        initjLabel();
        setTitle("メインメニュー");
        cardLayout = (CardLayout)jPanelCardBase.getLayout();
    }
    
    private void initjLabel(){
        jLabelErrorMesage.setForeground(Color.red);
   }
    
    /**
     * コントロールを設定
     * @param control 
     */
    public void setControl(SystemControl control){
        this.control = control;
    }
    
    public void loginFailure(){
        jLabelErrorMesage.setText("IDまたはパスワードが違います");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCardBase = new javax.swing.JPanel();
        jPaneMainMenu = new javax.swing.JPanel();
        jButtonEmoployyesMenu = new javax.swing.JButton();
        jButtonManagerMenu = new javax.swing.JButton();
        jPaneEmployeesMenu = new javax.swing.JPanel();
        jButtonOrder = new javax.swing.JButton();
        jButtonControlCustomer = new javax.swing.JButton();
        jPaneManegerMenu = new javax.swing.JPanel();
        jPaneLoginPanel = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelErrorMesage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setText("メインメニュー");

        jLabel2.setText("yyyy/MM/dd hh:mm:ss");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanelCardBase.setLayout(new java.awt.CardLayout());

        jPaneMainMenu.setBackground(new java.awt.Color(255, 255, 255));

        jButtonEmoployyesMenu.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonEmoployyesMenu.setText("従業員メニュー");
        jButtonEmoployyesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmoployyesMenuActionPerformed(evt);
            }
        });

        jButtonManagerMenu.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonManagerMenu.setText("マネージャーメニュー");
        jButtonManagerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneMainMenuLayout = new javax.swing.GroupLayout(jPaneMainMenu);
        jPaneMainMenu.setLayout(jPaneMainMenuLayout);
        jPaneMainMenuLayout.setHorizontalGroup(
            jPaneMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneMainMenuLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPaneMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonManagerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEmoployyesMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPaneMainMenuLayout.setVerticalGroup(
            jPaneMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneMainMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonEmoployyesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonManagerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanelCardBase.add(jPaneMainMenu, "card3");

        jPaneEmployeesMenu.setBackground(new java.awt.Color(255, 255, 255));

        jButtonOrder.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonOrder.setText("注文受付");
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButtonControlCustomer.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonControlCustomer.setText("顧客管理画面");
        jButtonControlCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneEmployeesMenuLayout = new javax.swing.GroupLayout(jPaneEmployeesMenu);
        jPaneEmployeesMenu.setLayout(jPaneEmployeesMenuLayout);
        jPaneEmployeesMenuLayout.setHorizontalGroup(
            jPaneEmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneEmployeesMenuLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPaneEmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonControlCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jPaneEmployeesMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonControlCustomer, jButtonOrder});

        jPaneEmployeesMenuLayout.setVerticalGroup(
            jPaneEmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneEmployeesMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonControlCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPaneEmployeesMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonControlCustomer, jButtonOrder});

        jPanelCardBase.add(jPaneEmployeesMenu, "card2");

        javax.swing.GroupLayout jPaneManegerMenuLayout = new javax.swing.GroupLayout(jPaneManegerMenu);
        jPaneManegerMenu.setLayout(jPaneManegerMenuLayout);
        jPaneManegerMenuLayout.setHorizontalGroup(
            jPaneManegerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPaneManegerMenuLayout.setVerticalGroup(
            jPaneManegerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        jPanelCardBase.add(jPaneManegerMenu, "card4");

        jPaneLoginPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel3.setText("従業員番号");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel4.setText("パスワード");

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButton1.setText("ログイン");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneLoginPanelLayout = new javax.swing.GroupLayout(jPaneLoginPanel);
        jPaneLoginPanel.setLayout(jPaneLoginPanelLayout);
        jPaneLoginPanelLayout.setHorizontalGroup(
            jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLoginPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorMesage)
                    .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPaneLoginPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPaneLoginPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(38, 38, 38)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPaneLoginPanelLayout.setVerticalGroup(
            jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLoginPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelErrorMesage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanelCardBase.add(jPaneLoginPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        control.showOrderBoundary();
    }//GEN-LAST:event_jButtonOrderActionPerformed
        
    private void jButtonControlCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlCustomerActionPerformed
        control.showCustomerBoundary();
    }//GEN-LAST:event_jButtonControlCustomerActionPerformed

    private void jButtonEmoployyesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmoployyesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEmoployyesMenuActionPerformed

    private void jButtonManagerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManagerMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        control.login();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuBoundary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonControlCustomer;
    private javax.swing.JButton jButtonEmoployyesMenu;
    private javax.swing.JButton jButtonManagerMenu;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelErrorMesage;
    private javax.swing.JPanel jPaneEmployeesMenu;
    private javax.swing.JPanel jPaneLoginPanel;
    private javax.swing.JPanel jPaneMainMenu;
    private javax.swing.JPanel jPaneManegerMenu;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCardBase;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
