/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sys;

import java.awt.CardLayout;

/**
 * 従業員メニューバウンダリー
 * @author 19jz0115
 */
public class MainMenuBoundary extends javax.swing.JFrame {
    private static final String CARD_MEIN_MENU = "card2";
    private static final String CARD_EMPLOYEES_MENU = "card3";
    private static final String CARD_MANAGER_MENU = "card4";
    private static final String CARD_LOGIN_MENU = "card5";
    private SystemControl control;
    private final CardLayout cardLayout;
    
    
    public MainMenuBoundary() {
        initComponents();
        setTitle("メインメニュー");
        cardLayout = (CardLayout)jPanelCardBase.getLayout();
    }
    
    /**
     * コントロールを設定
     * @param control 
     */
    public void setControl(SystemControl control){
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCardBase = new javax.swing.JPanel();
        MainMenu = new javax.swing.JPanel();
        jButtonEmoployyesMenu = new javax.swing.JButton();
        jButtonManagerMenu = new javax.swing.JButton();
        EmployeesMenu = new javax.swing.JPanel();
        jButtonOrder = new javax.swing.JButton();
        jButtonControlCustomer = new javax.swing.JButton();
        ManegerMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setText("メインメニュー");

        jLabel2.setText("yyyy/MM/dd hh:mm:ss");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanelCardBase.setLayout(new java.awt.CardLayout());

        MainMenu.setBackground(new java.awt.Color(255, 255, 255));

        jButtonEmoployyesMenu.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonEmoployyesMenu.setText("従業員メニュー");
        jButtonEmoployyesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmoployyesMenuActionPerformed(evt);
            }
        });

        jButtonManagerMenu.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonManagerMenu.setText("マネージャーメニュー");
        jButtonManagerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonManagerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEmoployyesMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonEmoployyesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonManagerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanelCardBase.add(MainMenu, "card3");

        EmployeesMenu.setBackground(new java.awt.Color(255, 255, 255));

        jButtonOrder.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonOrder.setText("注文受付");
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButtonControlCustomer.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonControlCustomer.setText("顧客管理画面");
        jButtonControlCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeesMenuLayout = new javax.swing.GroupLayout(EmployeesMenu);
        EmployeesMenu.setLayout(EmployeesMenuLayout);
        EmployeesMenuLayout.setHorizontalGroup(
            EmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeesMenuLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(EmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonControlCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        EmployeesMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonControlCustomer, jButtonOrder});

        EmployeesMenuLayout.setVerticalGroup(
            EmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeesMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonControlCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        EmployeesMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonControlCustomer, jButtonOrder});

        jPanelCardBase.add(EmployeesMenu, "card2");

        javax.swing.GroupLayout ManegerMenuLayout = new javax.swing.GroupLayout(ManegerMenu);
        ManegerMenu.setLayout(ManegerMenuLayout);
        ManegerMenuLayout.setHorizontalGroup(
            ManegerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ManegerMenuLayout.setVerticalGroup(
            ManegerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        jPanelCardBase.add(ManegerMenu, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        control.showOrderBoundary();
    }//GEN-LAST:event_jButtonOrderActionPerformed
        
    private void jButtonControlCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlCustomerActionPerformed
        control.showCustomerBoundary();
    }//GEN-LAST:event_jButtonControlCustomerActionPerformed

    private void jButtonEmoployyesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmoployyesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEmoployyesMenuActionPerformed

    private void jButtonManagerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManagerMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuBoundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuBoundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuBoundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuBoundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuBoundary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeesMenu;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel ManegerMenu;
    private javax.swing.JButton jButtonControlCustomer;
    private javax.swing.JButton jButtonEmoployyesMenu;
    private javax.swing.JButton jButtonManagerMenu;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCardBase;
    // End of variables declaration//GEN-END:variables
}
