/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sys;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Timer;

/**
 * 従業員メニューバウンダリー
 * @author 19jz0115
 */
public class MainMenuBoundary extends javax.swing.JFrame{
    private static final String CARD_EMPLOYEES_MENU = "card2";
    private static final String CARD_MAIN_MENU = "card3";
    private static final String CARD_MANAGER_MENU = "card4";
    private static final String CARD_LOGIN_MENU = "card5";
    private String showCard = CARD_MAIN_MENU;
    
    private SystemControl control;
    private final CardLayout cardLayout;
    
    
    public MainMenuBoundary() {
        initComponents();
        initjLabel();
        initButton();
        setTitle("メインメニュー");
        cardLayout = (CardLayout)jPanelCardBase.getLayout();
    }
    
    private void initjLabel(){
        jLabelErrorMesage.setForeground(Color.red);
   }
    
    /**
     * ボタンの初期化
     * デフォルト値 : false
     * デバッグ時   : true
     */
    private void initButton(){
        jButtonManagerMenu.setEnabled(true);
    }
    
    /**
     * コントロールを設定
     * @param control 
     */
    public void setControl(SystemControl control){
        this.control = control;
    }
    
    /**
     * カード切り替え処理
     */
    public void showCardLayout(String card){
        cardLayout.show(jPanelCardBase, card);
        showCard = card;
    }
    
    /**
     * ログイン失敗時の処理
     */
    public void loginFailure(){
        jLabelErrorMesage.setText("IDまたはパスワードが違います");
    }
    
    /**
     * ログイン成功時の処理
     */
    public void login(String employeeType){
        jLabelEmployeeNumber.setText(control.emp.getEmployeeNumber());
        jLabelEmployeeName.setText(control.emp.getEmployeeName());
        
        if(employeeType.equals("M")){
            jButtonManagerMenu.setEnabled(true);
        }
        jPasswordField.setText("");
        jButtonLoginLogout.setText("ログアウト");
        control.changeCardLayout(CARD_MAIN_MENU);
        jButtonLoginLogout.setVisible(true);
    }
    
    /**
     * ログアウト処理
     */
    public void logout(){
        jButtonManagerMenu.setEnabled(false);
        
        jLabelEmployeeNumber.setText("");
        jLabelEmployeeName.setText("");
        if(showCard == CARD_MANAGER_MENU){
            control.changeCardLayout(CARD_MAIN_MENU);
        }
        jButtonLoginLogout.setText("ログイン");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelEmployeeNumber = new javax.swing.JLabel();
        jLabelEmployeeName = new javax.swing.JLabel();
        jButtonLoginLogout = new javax.swing.JButton();
        jPanelCardBase = new javax.swing.JPanel();
        jPaneMainMenu = new javax.swing.JPanel();
        jButtonEmoployyesMenu = new javax.swing.JButton();
        jButtonManagerMenu = new javax.swing.JButton();
        jPaneEmployeesMenu = new javax.swing.JPanel();
        jButtonOrder = new javax.swing.JButton();
        jButtonControlCustomer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPaneManegerMenu = new javax.swing.JPanel();
        jButtonManageSales = new javax.swing.JButton();
        jButtonManageEmployee = new javax.swing.JButton();
        jButtonManageItem = new javax.swing.JButton();
        jPaneLoginPanel = new javax.swing.JPanel();
        jTextFieldEmployeeNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelErrorMesage = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setText("メインメニュー");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButtonLoginLogout.setText("ログイン");
        jButtonLoginLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLoginLogout)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonLoginLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEmployeeName)
                            .addComponent(jLabelEmployeeNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonLoginLogout, jLabelEmployeeName, jLabelEmployeeNumber});

        jPanelCardBase.setLayout(new java.awt.CardLayout());

        jPaneMainMenu.setBackground(new java.awt.Color(255, 255, 255));

        jButtonEmoployyesMenu.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonEmoployyesMenu.setText("従業員メニュー");
        jButtonEmoployyesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmoployyesMenuActionPerformed(evt);
            }
        });

        jButtonManagerMenu.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonManagerMenu.setText("マネージャーメニュー");
        jButtonManagerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneMainMenuLayout = new javax.swing.GroupLayout(jPaneMainMenu);
        jPaneMainMenu.setLayout(jPaneMainMenuLayout);
        jPaneMainMenuLayout.setHorizontalGroup(
            jPaneMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneMainMenuLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPaneMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonManagerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEmoployyesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPaneMainMenuLayout.setVerticalGroup(
            jPaneMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneMainMenuLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jButtonEmoployyesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonManagerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jPanelCardBase.add(jPaneMainMenu, "card3");

        jPaneEmployeesMenu.setBackground(new java.awt.Color(255, 255, 255));

        jButtonOrder.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonOrder.setText("注文受付");
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButtonControlCustomer.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonControlCustomer.setText("顧客管理画面");
        jButtonControlCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlCustomerActionPerformed(evt);
            }
        });

        jButton2.setText("メインメニューに戻る");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneEmployeesMenuLayout = new javax.swing.GroupLayout(jPaneEmployeesMenu);
        jPaneEmployeesMenu.setLayout(jPaneEmployeesMenuLayout);
        jPaneEmployeesMenuLayout.setHorizontalGroup(
            jPaneEmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneEmployeesMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(jPaneEmployeesMenuLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPaneEmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonControlCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPaneEmployeesMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonControlCustomer, jButtonOrder});

        jPaneEmployeesMenuLayout.setVerticalGroup(
            jPaneEmployeesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneEmployeesMenuLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonControlCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPaneEmployeesMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonControlCustomer, jButtonOrder});

        jPanelCardBase.add(jPaneEmployeesMenu, "card2");

        jPaneManegerMenu.setBackground(new java.awt.Color(255, 255, 255));

        jButtonManageSales.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonManageSales.setText("売上管理");
        jButtonManageSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageSalesActionPerformed(evt);
            }
        });

        jButtonManageEmployee.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonManageEmployee.setText("従業員管理");
        jButtonManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageEmployeeActionPerformed(evt);
            }
        });

        jButtonManageItem.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButtonManageItem.setText("商品管理");
        jButtonManageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneManegerMenuLayout = new javax.swing.GroupLayout(jPaneManegerMenu);
        jPaneManegerMenu.setLayout(jPaneManegerMenuLayout);
        jPaneManegerMenuLayout.setHorizontalGroup(
            jPaneManegerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneManegerMenuLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPaneManegerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonManageItem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPaneManegerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonManageSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonManageEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPaneManegerMenuLayout.setVerticalGroup(
            jPaneManegerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneManegerMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButtonManageSales, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonManageItem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPaneManegerMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonManageEmployee, jButtonManageItem, jButtonManageSales});

        jPanelCardBase.add(jPaneManegerMenu, "card4");

        jPaneLoginPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel3.setText("従業員番号");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel4.setText("パスワード");

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButton1.setText("ログイン");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jButton3.setText("メインメニューに戻る");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPasswordField.setText("jPasswordField1");

        javax.swing.GroupLayout jPaneLoginPanelLayout = new javax.swing.GroupLayout(jPaneLoginPanel);
        jPaneLoginPanel.setLayout(jPaneLoginPanelLayout);
        jPaneLoginPanelLayout.setHorizontalGroup(
            jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLoginPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelErrorMesage)
                    .addGroup(jPaneLoginPanelLayout.createSequentialGroup()
                        .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPaneLoginPanelLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPaneLoginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField, jTextFieldEmployeeNumber});

        jPaneLoginPanelLayout.setVerticalGroup(
            jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLoginPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelErrorMesage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPaneLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        jPanelCardBase.add(jPaneLoginPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        control.showOrderBoundary();
    }//GEN-LAST:event_jButtonOrderActionPerformed
        
    private void jButtonControlCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlCustomerActionPerformed
        control.showCustomerBoundary();
    }//GEN-LAST:event_jButtonControlCustomerActionPerformed

    private void jButtonEmoployyesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmoployyesMenuActionPerformed
        control.changeCardLayout(CARD_EMPLOYEES_MENU);
    }//GEN-LAST:event_jButtonEmoployyesMenuActionPerformed

    private void jButtonManagerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerMenuActionPerformed
        control.changeCardLayout(CARD_MANAGER_MENU);
    }//GEN-LAST:event_jButtonManagerMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        control.login(jTextFieldEmployeeNumber.getText(), jPasswordField.getPassword());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(showCard == CARD_LOGIN_MENU){
            jButtonLoginLogout.setVisible(true);
        }
        
        control.changeCardLayout(CARD_MAIN_MENU);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        control.changeCardLayout(CARD_MAIN_MENU);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        control.changeCardLayout(CARD_MAIN_MENU);
        jButtonLoginLogout.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonCheckSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckSalesActionPerformed
        control.showPaymentBoundary();
    }//GEN-LAST:event_jButtonCheckSalesActionPerformed

    private void jButtonManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageEmployeeActionPerformed
        control.showEmployeeBoundary();
    }//GEN-LAST:event_jButtonManageEmployeeActionPerformed

    private void jButtonLoginLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginLogoutActionPerformed
        if(control.LoginStatus == false){
            jTextFieldEmployeeNumber.setText("");
            jPasswordField.setText("");
            jLabelErrorMesage.setText("");
            jButtonLoginLogout.setVisible(false);
            control.changeCardLayout(CARD_LOGIN_MENU);
        }else{
            control.logout();
        }
    }//GEN-LAST:event_jButtonLoginLogoutActionPerformed

    private void jButtonManageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageItemActionPerformed
        control.showManageItemBoundary();
    }//GEN-LAST:event_jButtonManageItemActionPerformed
    
    
    private void jButtonManageSalesActionPerformed(java.awt.event.ActionEvent evt){
        control.showPaymentBoundary();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuBoundary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonControlCustomer;
    private javax.swing.JButton jButtonEmoployyesMenu;
    private javax.swing.JButton jButtonLoginLogout;
    private javax.swing.JButton jButtonManageEmployee;
    private javax.swing.JButton jButtonManageItem;
    private javax.swing.JButton jButtonManageSales;
    private javax.swing.JButton jButtonManagerMenu;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JLabel jLabelEmployeeNumber;
    private javax.swing.JLabel jLabelErrorMesage;
    private javax.swing.JPanel jPaneEmployeesMenu;
    private javax.swing.JPanel jPaneLoginPanel;
    private javax.swing.JPanel jPaneMainMenu;
    private javax.swing.JPanel jPaneManegerMenu;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCardBase;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldEmployeeNumber;
    // End of variables declaration//GEN-END:variables
}
